### ISSUE TITLE
4.2.0 release changed `IdentityClient.getInstance().validateIdentityOnToken` call return signature

### ISSUE THREAD

**Issue by mcmxcdev** [frontegg/nodejs-sdk#136]
https://github.com/frontegg/nodejs-sdk/releases/tag/4.2.0 changed the values returned from `IdentityClient.getInstance().validateIdentityOnToken`. Now `roles` and `permissions` are not returned anymore, which should be considered a breaking change.

This should've been a major version bump instead of a minor version according to semver. Teams who use dependency bots with automerge features would end up with a broken deployment.

**Comment by eran-frontegg** [comment]
Hi, @mcmxcdev,
Thanks for you noticing this change.
As it turns out the functions behavior did not change, and only the typing for it has.
We will release a fix with the previous typing soon.
Important to say - it is safe to use this version as the behavior hasn't changed.
