### ISSUE TITLE
Authenticator refresh token task runs indefinitely

### ISSUE THREAD

**Issue by shay-cyera** [frontegg/nodejs-sdk#37]
When using the frontegg client,  the authenticator start a task with setTimeout which runs indefinitely (the authenticator has no shutdown function). Leaving a task open when an app shuts down is bad practice and can also fail tests.
This also affects the getPublicKey function in the IdentityClient class, that in turn creates an authenticator, again starting a task that runs indefinitely (And actually the access token is needed only once).

Suggested fix:
Add a shutdown function to the authenticator, removing the refresh token timeout + in identity client, shutdown the authenticator after the key is retrieved.

Suggested PR:
#36

**Comment by aviadmizrachi** [comment]
Closed and merged
